### ISSUE TITLE
RSS Link Is Missing

### ISSUE THREAD

**Issue by Mehran-Baghi** [geekplux/hexo-theme-typing#10]
Hi
I have generated a RSS feed using the [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) and adding its location in the `_config.yml`. However there isn't any icon or link to the feed in the generated site. I guess it's meant to show up in the header:
layout/_partial/header.ejs:
```
    <% if (theme.rss){ %>
      <a id="nav-rss-link" class="nav-icon" href="<%- theme.rss %>" title="<%= __('rss_feed') %>"></a>
    <% } %>
```
my blog: https://mehranbaghi.com/
Feed: https://mehranbaghi.com/atom.xml

**Comment by geekplux** [comment]
@Mehran-Baghi thanks, done.

**Comment by Mehran-Baghi** [comment]
Thank you.
One more place to fix: Link is not inline nor has the same color (grey-bold) in the articles (posts) headers.
Suggestion: I think it makes more sense for RSS link to be in the right hand `float:right`.

**Comment by geekplux** [comment]
@Mehran-Baghi Thanks, welcome a PR
