### ISSUE TITLE
关于categories的问题

### ISSUE THREAD

**Issue by cloudpen** [geekplux/hexo-theme-typing#16]
主题很漂亮，稍作调整，用得很方便。但有一个问题，生成好的categories上，无法显示具体内容，只是空白一片。

**Comment by geekplux** [comment]
我刚试了下，你是说 /categories  和 /tags ？这两个 url 本来就没页面吧，官方主题的 layout 里是没有这两个的单独页面的，只有 /categories/aaa 或 /tags/bbb
