### ISSUE TITLE
关于首页menu显示的问题

### ISSUE THREAD

**Issue by wessmrs** [geekplux/hexo-theme-typing#17]
很喜欢你的主题，但是在部署的时候遇到一个布局的问题，菜单栏会展示两个，不知有没有人遇到过。
<img width="604" alt="2018-01-21 13 17 24" src="https://user-images.githubusercontent.com/34997786/35191122-78e8a2ca-fead-11e7-9459-b0e42a279fdd.png">

**Comment by geekplux** [comment]
你试试把 config.yml 里的 icon 改成 false

**Comment by wessmrs** [comment]
已找到问题，抱歉，是hexo的配置出现了失误。
感谢博主的优美主题~
