### ISSUE TITLE
How to enable disqus comment?

### ISSUE THREAD

**Issue by iqbwl** [geekplux/hexo-theme-typing#18]
I can't enable disqus comment. I remove gitment and I try to enable disqus. but not work.

**Comment by geekplux** [comment]
just set `disqus_shortname` in your `config.yml` which in your blog root folder.

I'll add `disqus_shortname` into theme `config.yml` later.

**Comment by iqbwl** [comment]
I have been set `disqus_shortname`.
but, not work.. only gitment is work

**Comment by geekplux** [comment]
How can I reappear this issue

**Comment by iqbwl** [comment]
I don't know..

**Comment by xCss** [comment]
please set `disqus_shortname` in your **site** `_config.yml`, not in **theme** `_config.yml`

more info please see [layout/_partial/after-footer.ejs#L1](https://github.com/geekplux/hexo-theme-typing/blob/master/layout/_partial/after-footer.ejs#L1) and [layout/_partial/article.ejs#L73](https://github.com/geekplux/hexo-theme-typing/blob/master/layout/_partial/article.ejs#L73)
