### ISSUE TITLE
page of categories display error

### ISSUE THREAD

**Issue by moreoronce** [geekplux/hexo-theme-typing#2]
[categories' page](https://i.v2ex.co/hpzDJPve.jpeg)

seems this page's style do not as same as archives' page

Is it a error or just made it like that?

**Comment by geekplux** [comment]
forgive me that just forget the category page...I'll fix it

**Comment by geekplux** [comment]
@moreoronce Hi, is the category page created by `hexo new page` ? so your own page would present like About page etc.

**Comment by moreoronce** [comment]
@geekplux i captured this page from the demo website but my site have the same problem too. i forgot how i created this page. seems it was automatic created by hexo itself.

**Comment by moreoronce** [comment]
@geekplux and i found another place seems can be optimized. In the article page, there were no link to back to the home page or archives page. Only two link to next article or previous article.

**Comment by geekplux** [comment]
has added the nav link..
