### ISSUE TITLE
请问如何进入博客时直接显示文章列表页面

### ISSUE THREAD

**Issue by zemora** [geekplux/hexo-theme-typing#20]
您好：感谢您制作的优秀主题！我想在点击博客网址时不要显示开始的 Nickname, description 这些东西，直接显示文章列表页，不知道应该怎么设置？此外文章列表页下面还有个 description ，我想把这块也一并去掉。可以在模板中增加这样的设置吗？

**Comment by geekplux** [comment]
1. 直接显示列表页，设置 hexo config 的 root url
2. 其他：设置我主题 config

请在提问前认真阅读文档，谢谢
