### ISSUE TITLE
请问“关于”界面如何添加？

### ISSUE THREAD

**Issue by seanM29** [geekplux/hexo-theme-typing#22]
在你的blog中有一个"关于我"界面
目前想到的就是写一个“关于”博客，但是这样在Archives中也会多出这篇blog
请问你是如何添加实现的？
谢谢！！

**Comment by geekplux** [comment]
这是 hexo 的功能，运行 `hexo new page` 会生成一个**页面**，而不是**博文(post)**

PS: 再次建议：请认真阅读文档，还有学会搜索。谢谢

**Comment by seanM29** [comment]
嗯嗯 因为对hexo不是特别熟悉 很抱歉提出这样的问题
谢谢！
