### ISSUE TITLE
关闭打赏功能选项

### ISSUE THREAD

**Issue by yzhangcs** [geekplux/hexo-theme-typing#23]
感谢您的优美主题
但是我尝试着用您的主题搭建博客，进入博客界面底部会有打赏功能，并且好像无法关闭
我不太想要这个功能，所以问问是否可以在打赏选项下设置enable: false功能，让其不再显示
谢谢！

**Comment by geekplux** [comment]
是说每篇文章最后吗？方便截个图？
我会改一下

**Comment by yzhangcs** [comment]
是的
![image](https://user-images.githubusercontent.com/18402347/42209448-3e9ace90-7ee1-11e8-9233-b74ff003baec.png)
希望能够这样：
```sh
donate:
  enable: false
```
然后不再显示
谢谢

**Comment by geekplux** [comment]
OK，晚上我看看

**Comment by geekplux** [comment]
fixed by #26
