### ISSUE TITLE
动态平滑载入的效果在Chrome和Firefox上没有显示

### ISSUE THREAD

**Issue by yzhangcs** [geekplux/hexo-theme-typing#24]
在Edge上加载页面会有下面的效果
![demo](https://user-images.githubusercontent.com/18402347/42219042-19760fe6-7efd-11e8-9a9f-38cffa1667d5.gif)
但是在Chrome和Firefox上这个效果却消失了
这种平滑载入的效果在这两个浏览器上不兼容吗

**Comment by geekplux** [comment]
应该都有，估计是。。Edge 太慢了？？

**Comment by yzhangcs** [comment]
嗯，可能是吧
不过我觉得页面跳转有点生硬，觉得加载效果像下面的那样，更加平滑会好一点
![demo](https://user-images.githubusercontent.com/18402347/42281511-50d278f6-7fd6-11e8-95d3-f53c64b5481c.gif)
也可能我们的审美不同
希望您能采纳，谢谢
