### ISSUE TITLE
使用mathjx数学环境在每一页左下方会有mathjx的cdn

### ISSUE THREAD

**Issue by chtld** [geekplux/hexo-theme-typing#27]
碰到的情况如图所示：
![1](https://user-images.githubusercontent.com/35769765/46070679-f72b1200-c1b0-11e8-8ff8-5e5fe5953337.png)

**Comment by chtld** [comment]
原因是生成的public文件夹中的index.html中出现下面的句子：
![3](https://user-images.githubusercontent.com/35769765/46071204-19715f80-c1b2-11e8-916f-7f14d1889da4.png)

**Comment by geekplux** [comment]
你 config.yml 怎么写的呀

**Comment by chtld** [comment]
问题已解决。在\node_modules\hexo-renderer-mathjax这个文件夹下如下文件中的语句由于我自己的原因改动错误。感谢作者。
![5](https://user-images.githubusercontent.com/35769765/46086900-bb597200-c1db-11e8-9a5b-f5b3fb2cdba7.png)

**Comment by fsZhuangB** [comment]
> 碰到的情况如图所示：
> ![1](https://user-images.githubusercontent.com/35769765/46070679-f72b1200-c1b0-11e8-8ff8-5e5fe5953337.png)

你好，请问如何开启数学环境呢，搜索了一些博客，但是还不行，没有渲染成功
