### ISSUE TITLE
The padding of line number in code block is too small.

### ISSUE THREAD

**Issue by loveminimal** [geekplux/hexo-theme-typing#33]
When I write js code here, the line numbers is so close to the code. Have you  met the same question, and can you adjust the style of it ?

**Comment by geekplux** [comment]
sorry for late reply. It may be some style incorrect of highlight CSS.

**Comment by loveminimal** [comment]
> sorry for late reply. It may be some style incorrect of highlight CSS.

I have a try, but failed. hah.. , I cannont master hexo at this time. Waiting for your updating. Thank you, sir.
