### ISSUE TITLE
Mobile navigation menu without javascript

### ISSUE THREAD

**Issue by curbengh** [geekplux/hexo-theme-typing#34]
@geekplux 
I recently stumbled upon https://github.com/paulcarl/skelepico-theme, what intrigued me is the theme's mobile navigation menu is implemented without javascript (preview https://paulcarl.com/skelepico/).

I ported it to this theme, and if you're interested, I can submit a PR. I didn't implement the 'sticky' menu (always display on top of page) as I don't like it.

Otherwise, you may close this.

**Comment by curbengh** [comment]
Preview:

- Mobile menu
![normal](https://user-images.githubusercontent.com/43627182/48043790-57fa3100-e1d8-11e8-8776-3855f761e2cd.png)
- Menu clicked (current)
![current](https://user-images.githubusercontent.com/43627182/48043793-5892c780-e1d8-11e8-86f6-6113c6b6bc8d.png)
- Menu clicked (my implementation)
![no-js](https://user-images.githubusercontent.com/43627182/48043792-5892c780-e1d8-11e8-9974-c536f0effda2.png)

**Comment by geekplux** [comment]
welcome PRs. I implemented this mobile menu in a hurry before, you can make a better one.

**Comment by curbengh** [comment]
Cool. I added border to the menu. We need to decide the css values:

- [x] border thickness = 2px
- [ ] border color (dark theme) = `#999`
- [ ] border color (light theme) = 
- [x] display = grid
- `display:block;`
![display-block](https://user-images.githubusercontent.com/43627182/48101906-9810f080-e278-11e8-88b1-fb8ee0ef8059.png)
- `display:grid;`
![display-grid](https://user-images.githubusercontent.com/43627182/48101917-a232ef00-e278-11e8-9e31-b0624fd028ca.png)

you can play around with the css values here (look for `#menu`): https://weyusi.github.io/hexo-testing/2018/10/05/hello-world/

The preview is currently dark theme; once we okay with most of values, we can then decide on light theme's border color.

let me know if `margin` or `padding` need to change too, I don't have any preference. Except for `text-alight`, which I prefer it to be `center` for nav menu.

**Comment by geekplux** [comment]
some config I prefer:


```css
{
    border: 2px solid #999;
    border-radius: 3px;
    display: grid;
    margin-top: 5px;
    text-align: right;
    padding: 5px 20px;
}
```
make `text-align` be `right` because alignment is important.

what do you think?

**Comment by curbengh** [comment]
yeah, center text-align does look weird when the text is long. FB, Patreon, GitHub and GitLab use left though, what do you think?

**Comment by geekplux** [comment]
lol, ok, follow your advice

**Comment by curbengh** [comment]
Alright, on to light theme. `#999999`, or `#cfcfcf` (same as `<hr>`) or any other?

I've switched https://weyusi.github.io/hexo-testing/2018/10/05/hello-world/ to light theme.

**Comment by geekplux** [comment]
I think `#999` may be better. and could you please set `position: absolute` ? 😆

<img width="336" alt="2018-11-09 4 11 30" src="https://user-images.githubusercontent.com/3816105/48250698-254f7300-e43a-11e8-9524-e236e9e9e50f.png">
<img width="340" alt="2018-11-09 4 06 15" src="https://user-images.githubusercontent.com/3816105/48250705-28e2fa00-e43a-11e8-961e-f435e1cbd79e.png">

**Comment by curbengh** [comment]
added `absolute`.

**Comment by curbengh** [comment]
After https://github.com/geekplux/hexo-theme-typing/pull/35, I notice when hovering the Menu button, it underlines in [post](https://weyusi.github.io/hexo-testing/2018/10/05/hello-world/), but not in [archives page](https://weyusi.github.io/hexo-testing/archives/).

I think the appearance of Menu button should be consistent. Underline or not?

**Comment by geekplux** [comment]
Initially, I remember the links in `article-entry` are with underlined when it hovered, and the links in menu are not.

**Comment by curbengh** [comment]
got it, no underline in menu then.
