### ISSUE TITLE
可以考虑加一个段落目录?

### ISSUE THREAD

**Issue by TomorJM** [geekplux/hexo-theme-typing#4]
放在文章右面,就更棒了

**Comment by geekplux** [comment]
(⊙v⊙)嗯，可能我太固执，最开始想的是文章阅读界面，什么按钮都没有，只有文章和footer。。
如果真的需要的话，我可以开发一个，可设置是否显示的目录

**Comment by TomorJM** [comment]
嘿嘿,实在太喜欢你这种设计风格了,期盼你能加上doc目录,那样就更完美了。
还有,实在不好意思的是,为了美观,我把我自己博客首页的footer给去掉了,后面我会抓们写一篇迁移博客的文章注上你的署名,望原谅

**Comment by geekplux** [comment]
没事，给开源社区贡献有个署名就不错了 :)
我抽空写
