### ISSUE TITLE
如何显示文章?

### ISSUE THREAD

**Issue by SiegFriedrich** [geekplux/hexo-theme-typing#48]
你好!我是刚刚玩hexo博客的,我觉得你的模板很好看,下载了你的模板.
替换掉主题后,原先的Hello World文章没有显示出来. 想请教以下应该怎么设置.

**Comment by geekplux** [comment]
感谢关注这个主题，如果是按 hexo 的标准目录结构应该是不用其他配置。不过我不知道新版hexo是否做了改动
