### ISSUE TITLE
Question about `make css`

### ISSUE THREAD

**Issue by chempeng** [geekplux/hexo-theme-typing#6]
感谢您在博客中耐心的回复解答 (http://disq.us/p/1hnytaj) ，我尝试解决了下，仍然有点问题向您请教。问题可能有些小白，见谅见谅

1. 运行 `make css` 命令时，出现如下情况，不知是出了什么问题
```

E:\Hexo\themes\typing>cmd
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

E:\Hexo\themes\typing>make css
./node_modules/.bin/postcss --use postcss-import --use precss --use autoprefixer
 --use cssnano source/css/source.css --output source/css/typing.css
make: ./node_modules/.bin/postcss: Command not found
make: *** [css] Error 127

E:\Hexo\themes\typing>
```

2. 下面是您的博客文章在我的手机端的显示效果，感觉确实挺窄的
http://olajpy11a.bkt.clouddn.com/17-4-8/13378215-file_1491653401170_112b3.png

**Comment by geekplux** [comment]
噢噢，这个你需要先安装依赖，在项目根目录下：

```
npm install
```

**Comment by geekplux** [comment]
具体修改 source.css 中的 `$content-width` 还有 `$mobile-content-width`

**Comment by chempeng** [comment]
The problem is solved successfully, thanks for your help
