### ISSUE TITLE
Problem with default language

### ISSUE THREAD

**Issue by Mehran-Baghi** [geekplux/hexo-theme-typing#7]
Hi
First of all Thank you for this beautiful theme.
I had an issue with the default language. I wanted it to be english. But it sometimes becames "es" or ... However I solved the problem by copying the default.yml and making an en.yml and then changing the language config to "en".

**Comment by geekplux** [comment]
I will have a try to reproduce this problem.

**Comment by Mehran-Baghi** [comment]
Thank you.
here are steps to reproduce it:
```
hexo init test
cd ./test
npm install
git clone https://github.com/geekplux/hexo-theme-typing themes/typing
```
```
./_config.yml ----> theme: typing
```
```
hexo new post test
```
```
tags:
categories:
- Sports
---
```
```
hexo server
```
and in browser sometimes it shows "Categoría" but sometimes it's "Category"
however if I do the following steps:
```
cp default.yml en.yml
```
```
/test/_config.yml ----> language: "en"
```
problem will be solved.

**Comment by geekplux** [comment]
yes, same error I met.
I think you have found the solution, and can you send me a PR to fix this?

**Comment by Mehran-Baghi** [comment]
sure...
#8

**Comment by geekplux** [comment]
thanks! 👍👍👍

**Comment by Mehran-Baghi** [comment]
We have to modify `_config.yml` to `language: "en"` too. I have added the instruction to the README.md in a separate PR #9 .
This solves the problem. However I'm not sure whether this problem is caused by your theme or hexo itself.

**Comment by geekplux** [comment]
I don't know, too. But I think these both have problems.
